package public

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

var (
	ErrRequestAuth                  = echo.NewHTTPError(http.StatusUnauthorized, "Authorization is required")
	ErrInferenceParticipantNotFound = echo.NewHTTPError(http.StatusNotFound, "Inference participant not found")
	ErrInsufficientBalance          = echo.NewHTTPError(http.StatusPaymentRequired, "Insufficient balance")

	ErrIdRequired                                      = echo.NewHTTPError(http.StatusBadRequest, "Id is required")
	ErrAddressRequired                                 = echo.NewHTTPError(http.StatusBadRequest, "Address is required")
	ErrInvalidEpochId                                  = echo.NewHTTPError(http.StatusBadRequest, "Invalid epoch id")
	ErrInvalidTrainingJobId                            = echo.NewHTTPError(http.StatusBadRequest, "Invalid training job id")
	ErrEpochIsNotReached                               = echo.NewHTTPError(http.StatusBadRequest, "Epoch is not reached")
	ErrInferenceNotFound                               = echo.NewHTTPError(http.StatusNotFound, "Inference not found")
	ErrNoModelSpecified                                = echo.NewHTTPError(http.StatusBadRequest, "No model specified")
	ErrV2EscrowIDRequired                              = echo.NewHTTPError(http.StatusBadRequest, "X-Escrow-Id header required")
	ErrV2EscrowSequenceRequired                        = echo.NewHTTPError(http.StatusBadRequest, "X-Escrow-Sequence header required")
	ErrV2EscrowSequenceInvalid                         = echo.NewHTTPError(http.StatusBadRequest, "X-Escrow-Sequence must be a positive integer")
	ErrV2EpochIDRequired                               = echo.NewHTTPError(http.StatusBadRequest, "X-Epoch-Id header required")
	ErrV2EpochIDInvalid                                = echo.NewHTTPError(http.StatusBadRequest, "X-Epoch-Id must be a positive integer")
	ErrV2EscrowEpochUnavailable                        = echo.NewHTTPError(http.StatusServiceUnavailable, "Escrow epoch_id unavailable")
	ErrV2EscrowEpochMismatch                           = echo.NewHTTPError(http.StatusConflict, "X-Epoch-Id does not match escrow epoch_id")
	ErrV2EscrowSequenceNotIncreasing                   = echo.NewHTTPError(http.StatusConflict, "X-Escrow-Sequence must be strictly increasing for this escrow_id")
	ErrV2RequesterRequired                             = echo.NewHTTPError(http.StatusBadRequest, "X-Requester-Address header required")
	ErrV2EscrowNotAuthorized                           = echo.NewHTTPError(http.StatusForbidden, "Requester does not have access to this escrow_id")
	ErrV2EscrowModelMismatch                           = echo.NewHTTPError(http.StatusForbidden, "Escrow model_id does not match request model")
	ErrV2ParticipantNotResponsible                     = echo.NewHTTPError(http.StatusForbidden, "This participant is not responsible for escrow_id+sequence")
	ErrV2ParticipantAddressUnavailable                 = echo.NewHTTPError(http.StatusServiceUnavailable, "Unable to resolve participant address")
	ErrV2OpenAIRequestRequired                         = echo.NewHTTPError(http.StatusBadRequest, "openai_request field is required")
	ErrV2OpenAIRequestInvalid                          = echo.NewHTTPError(http.StatusBadRequest, "openai_request must be a valid OpenAI request object")
	ErrV2DeveloperChainDeltaRequired                   = echo.NewHTTPError(http.StatusBadRequest, "developer_chain_delta field is required")
	ErrV2DeveloperChainDeltaBlocksRequired             = echo.NewHTTPError(http.StatusBadRequest, "developer_chain_delta.blocks must contain at least one block")
	ErrV2DeveloperChainDeltaTooLarge                   = echo.NewHTTPError(http.StatusRequestEntityTooLarge, "developer_chain_delta exceeds size limits")
	ErrV2DeveloperChainDeltaMalformed                  = echo.NewHTTPError(http.StatusBadRequest, "developer_chain_delta payload is malformed")
	ErrV2DeveloperChainDeltaBaseBlockSequenceMismatch  = echo.NewHTTPError(http.StatusConflict, "developer_chain_delta.base_block_sequence does not match receiver checkpoint")
	ErrV2DeveloperChainDeltaContinuityInvalid          = echo.NewHTTPError(http.StatusConflict, "developer_chain_delta block_sequence continuity is invalid")
	ErrV2DeveloperChainDeltaOverlapMismatch            = echo.NewHTTPError(http.StatusConflict, "developer_chain_delta overlap does not match receiver chain")
	ErrV2DeveloperChainDeltaCurrentRequestMismatch     = echo.NewHTTPError(http.StatusConflict, "latest block StartInference.request_id does not match current request")
	ErrV2DeveloperChainDeltaRequestPayloadHashMismatch = echo.NewHTTPError(http.StatusConflict, "latest block StartInference.request_payload_hash does not match openai_request payload")
	ErrV2DeveloperBlockSignatureRequired               = echo.NewHTTPError(http.StatusBadRequest, "developer_chain_delta block signature fields are required")
	ErrV2DeveloperBlockSignatureEncodingInvalid        = echo.NewHTTPError(http.StatusBadRequest, "developer_chain_delta block signature encoding is invalid")
	ErrV2DeveloperBlockSignatureInvalid                = echo.NewHTTPError(http.StatusUnauthorized, "developer_chain_delta block signature is invalid")
	ErrV2FinishInferenceProofRequired                  = echo.NewHTTPError(http.StatusBadRequest, "FinishInference executor proof fields are required")
	ErrV2FinishInferenceProofInvalid                   = echo.NewHTTPError(http.StatusUnauthorized, "FinishInference executor proof is invalid")
	ErrV2FinishInferenceSignerUnauthorized             = echo.NewHTTPError(http.StatusUnauthorized, "FinishInference executor signer is not authorized")
	ErrV2ExecutorSignerPubKeyUnavailable               = echo.NewHTTPError(http.StatusServiceUnavailable, "Executor signer public key unavailable")
	ErrV2RequesterPubKeyUnavailable                    = echo.NewHTTPError(http.StatusServiceUnavailable, "Requester public key unavailable")
	ErrV2IntendedExecutorUnavailable                   = echo.NewHTTPError(http.StatusServiceUnavailable, "Intended executor unavailable")
	ErrV2RequestIDConflict                             = echo.NewHTTPError(http.StatusConflict, "request_id conflicts with an existing request payload")
	ErrV2RequestInProgress                             = echo.NewHTTPError(http.StatusConflict, "request_id is already in progress")
	ErrV2RequestAlreadyProcessed                       = echo.NewHTTPError(http.StatusConflict, "request_id already processed without replayable response")
)
