FROM golang:1.24.2-alpine3.20 AS builder
RUN apk add --no-cache zip

WORKDIR /build
COPY subnet/ .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -tags versiond -o subnetctl ./cmd/subnetctl/

RUN mkdir -p /srv/files && \
    zip -j /srv/files/subnetctl.zip subnetctl && \
    sha256sum /srv/files/subnetctl.zip | cut -d' ' -f1 > /srv/files/subnetctl.zip.sha256

FROM python:3.12-alpine
COPY --from=builder /srv/files /srv/files

WORKDIR /srv/files
EXPOSE 8080
CMD ["python3", "-m", "http.server", "8080"]
