// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: poc/propagation/proto/propagation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropagationHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      []byte                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Participant   string                 `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	PocHeight     int64                  `protobuf:"varint,3,opt,name=poc_height,json=pocHeight,proto3" json:"poc_height,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Count         uint32                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagationHeader) Reset() {
	*x = PropagationHeader{}
	mi := &file_poc_propagation_proto_propagation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagationHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagationHeader) ProtoMessage() {}

func (x *PropagationHeader) ProtoReflect() protoreflect.Message {
	mi := &file_poc_propagation_proto_propagation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagationHeader.ProtoReflect.Descriptor instead.
func (*PropagationHeader) Descriptor() ([]byte, []int) {
	return file_poc_propagation_proto_propagation_proto_rawDescGZIP(), []int{0}
}

func (x *PropagationHeader) GetBundleId() []byte {
	if x != nil {
		return x.BundleId
	}
	return nil
}

func (x *PropagationHeader) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

func (x *PropagationHeader) GetPocHeight() int64 {
	if x != nil {
		return x.PocHeight
	}
	return 0
}

func (x *PropagationHeader) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *PropagationHeader) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PropagationHeader) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PropagationHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_poc_propagation_proto_propagation_proto protoreflect.FileDescriptor

const file_poc_propagation_proto_propagation_proto_rawDesc = "" +
	"\n" +
	"'poc/propagation/proto/propagation.proto\x12\vpropagation\"\xe1\x01\n" +
	"\x11PropagationHeader\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\fR\bbundleId\x12 \n" +
	"\vparticipant\x18\x02 \x01(\tR\vparticipant\x12\x1d\n" +
	"\n" +
	"poc_height\x18\x03 \x01(\x03R\tpocHeight\x12\x1b\n" +
	"\troot_hash\x18\x04 \x01(\fR\brootHash\x12\x14\n" +
	"\x05count\x18\x05 \x01(\rR\x05count\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignatureB,Z*decentralized-api/poc/propagation/proto;pbb\x06proto3"

var (
	file_poc_propagation_proto_propagation_proto_rawDescOnce sync.Once
	file_poc_propagation_proto_propagation_proto_rawDescData []byte
)

func file_poc_propagation_proto_propagation_proto_rawDescGZIP() []byte {
	file_poc_propagation_proto_propagation_proto_rawDescOnce.Do(func() {
		file_poc_propagation_proto_propagation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poc_propagation_proto_propagation_proto_rawDesc), len(file_poc_propagation_proto_propagation_proto_rawDesc)))
	})
	return file_poc_propagation_proto_propagation_proto_rawDescData
}

var file_poc_propagation_proto_propagation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_poc_propagation_proto_propagation_proto_goTypes = []any{
	(*PropagationHeader)(nil), // 0: propagation.PropagationHeader
}
var file_poc_propagation_proto_propagation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poc_propagation_proto_propagation_proto_init() }
func file_poc_propagation_proto_propagation_proto_init() {
	if File_poc_propagation_proto_propagation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poc_propagation_proto_propagation_proto_rawDesc), len(file_poc_propagation_proto_propagation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poc_propagation_proto_propagation_proto_goTypes,
		DependencyIndexes: file_poc_propagation_proto_propagation_proto_depIdxs,
		MessageInfos:      file_poc_propagation_proto_propagation_proto_msgTypes,
	}.Build()
	File_poc_propagation_proto_propagation_proto = out.File
	file_poc_propagation_proto_propagation_proto_goTypes = nil
	file_poc_propagation_proto_propagation_proto_depIdxs = nil
}
