// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/poc_v2.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoCArtifactV2 represents a single artifact from PoC v2 generation.
// Used for local off-chain storage and proof verification.
type PoCArtifactV2 struct {
	Nonce  int32  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Vector []byte `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
}

func (m *PoCArtifactV2) Reset()         { *m = PoCArtifactV2{} }
func (m *PoCArtifactV2) String() string { return proto.CompactTextString(m) }
func (*PoCArtifactV2) ProtoMessage()    {}
func (*PoCArtifactV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{0}
}
func (m *PoCArtifactV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCArtifactV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCArtifactV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCArtifactV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCArtifactV2.Merge(m, src)
}
func (m *PoCArtifactV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCArtifactV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCArtifactV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCArtifactV2 proto.InternalMessageInfo

func (m *PoCArtifactV2) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *PoCArtifactV2) GetVector() []byte {
	if m != nil {
		return m.Vector
	}
	return nil
}

// PoCValidationV2 represents a validator's attestation of a participant's PoC work.
// validated_weight: -1 = reject/fraud, >0 = accept
type PoCValidationV2 struct {
	ParticipantAddress          string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	ValidatorParticipantAddress string `protobuf:"bytes,2,opt,name=validator_participant_address,json=validatorParticipantAddress,proto3" json:"validator_participant_address,omitempty"`
	PocStageStartBlockHeight    int64  `protobuf:"varint,3,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	ValidatedWeight             int64  `protobuf:"varint,4,opt,name=validated_weight,json=validatedWeight,proto3" json:"validated_weight,omitempty"`
}

func (m *PoCValidationV2) Reset()         { *m = PoCValidationV2{} }
func (m *PoCValidationV2) String() string { return proto.CompactTextString(m) }
func (*PoCValidationV2) ProtoMessage()    {}
func (*PoCValidationV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{1}
}
func (m *PoCValidationV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationV2.Merge(m, src)
}
func (m *PoCValidationV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationV2 proto.InternalMessageInfo

func (m *PoCValidationV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetValidatorParticipantAddress() string {
	if m != nil {
		return m.ValidatorParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCValidationV2) GetValidatedWeight() int64 {
	if m != nil {
		return m.ValidatedWeight
	}
	return 0
}

// PoCValidationPayloadV2 is the message payload for validation submission.
// Height is at message level, validator derived from signer.
type PoCValidationPayloadV2 struct {
	ParticipantAddress string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	ValidatedWeight    int64  `protobuf:"varint,2,opt,name=validated_weight,json=validatedWeight,proto3" json:"validated_weight,omitempty"`
}

func (m *PoCValidationPayloadV2) Reset()         { *m = PoCValidationPayloadV2{} }
func (m *PoCValidationPayloadV2) String() string { return proto.CompactTextString(m) }
func (*PoCValidationPayloadV2) ProtoMessage()    {}
func (*PoCValidationPayloadV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{2}
}
func (m *PoCValidationPayloadV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationPayloadV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationPayloadV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationPayloadV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationPayloadV2.Merge(m, src)
}
func (m *PoCValidationPayloadV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationPayloadV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationPayloadV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationPayloadV2 proto.InternalMessageInfo

func (m *PoCValidationPayloadV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCValidationPayloadV2) GetValidatedWeight() int64 {
	if m != nil {
		return m.ValidatedWeight
	}
	return 0
}

// MLNodeWeight represents artifact count attributed to a single node.
type MLNodeWeight struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Weight uint32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (m *MLNodeWeight) Reset()         { *m = MLNodeWeight{} }
func (m *MLNodeWeight) String() string { return proto.CompactTextString(m) }
func (*MLNodeWeight) ProtoMessage()    {}
func (*MLNodeWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{3}
}
func (m *MLNodeWeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MLNodeWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MLNodeWeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MLNodeWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLNodeWeight.Merge(m, src)
}
func (m *MLNodeWeight) XXX_Size() int {
	return m.Size()
}
func (m *MLNodeWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_MLNodeWeight.DiscardUnknown(m)
}

var xxx_messageInfo_MLNodeWeight proto.InternalMessageInfo

func (m *MLNodeWeight) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MLNodeWeight) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// PoCV2StoreCommit stores the off-chain artifact store state.
type PoCV2StoreCommit struct {
	ParticipantAddress       string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	PocStageStartBlockHeight int64  `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Count                    uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	RootHash                 []byte `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	CommitBlockHeight        int64  `protobuf:"varint,5,opt,name=commit_block_height,json=commitBlockHeight,proto3" json:"commit_block_height,omitempty"`
}

func (m *PoCV2StoreCommit) Reset()         { *m = PoCV2StoreCommit{} }
func (m *PoCV2StoreCommit) String() string { return proto.CompactTextString(m) }
func (*PoCV2StoreCommit) ProtoMessage()    {}
func (*PoCV2StoreCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{4}
}
func (m *PoCV2StoreCommit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCV2StoreCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCV2StoreCommit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCV2StoreCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCV2StoreCommit.Merge(m, src)
}
func (m *PoCV2StoreCommit) XXX_Size() int {
	return m.Size()
}
func (m *PoCV2StoreCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCV2StoreCommit.DiscardUnknown(m)
}

var xxx_messageInfo_PoCV2StoreCommit proto.InternalMessageInfo

func (m *PoCV2StoreCommit) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCV2StoreCommit) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCV2StoreCommit) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PoCV2StoreCommit) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *PoCV2StoreCommit) GetCommitBlockHeight() int64 {
	if m != nil {
		return m.CommitBlockHeight
	}
	return 0
}

// MLNodeWeightDistribution stores per-node weight distribution.
type MLNodeWeightDistribution struct {
	ParticipantAddress       string          `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	PocStageStartBlockHeight int64           `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Weights                  []*MLNodeWeight `protobuf:"bytes,3,rep,name=weights,proto3" json:"weights,omitempty"`
}

func (m *MLNodeWeightDistribution) Reset()         { *m = MLNodeWeightDistribution{} }
func (m *MLNodeWeightDistribution) String() string { return proto.CompactTextString(m) }
func (*MLNodeWeightDistribution) ProtoMessage()    {}
func (*MLNodeWeightDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{5}
}
func (m *MLNodeWeightDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MLNodeWeightDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MLNodeWeightDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MLNodeWeightDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLNodeWeightDistribution.Merge(m, src)
}
func (m *MLNodeWeightDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MLNodeWeightDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MLNodeWeightDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MLNodeWeightDistribution proto.InternalMessageInfo

func (m *MLNodeWeightDistribution) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *MLNodeWeightDistribution) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *MLNodeWeightDistribution) GetWeights() []*MLNodeWeight {
	if m != nil {
		return m.Weights
	}
	return nil
}

type PocCountEntry struct {
	Participant string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	Count       uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *PocCountEntry) Reset()         { *m = PocCountEntry{} }
func (m *PocCountEntry) String() string { return proto.CompactTextString(m) }
func (*PocCountEntry) ProtoMessage()    {}
func (*PocCountEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{6}
}
func (m *PocCountEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PocCountEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PocCountEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PocCountEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PocCountEntry.Merge(m, src)
}
func (m *PocCountEntry) XXX_Size() int {
	return m.Size()
}
func (m *PocCountEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PocCountEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PocCountEntry proto.InternalMessageInfo

func (m *PocCountEntry) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *PocCountEntry) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PocCount struct {
	Creator                  string           `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PocStageStartBlockHeight int64            `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Entries                  []*PocCountEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	BlockHeight              int64            `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *PocCount) Reset()         { *m = PocCount{} }
func (m *PocCount) String() string { return proto.CompactTextString(m) }
func (*PocCount) ProtoMessage()    {}
func (*PocCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{7}
}
func (m *PocCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PocCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PocCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PocCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PocCount.Merge(m, src)
}
func (m *PocCount) XXX_Size() int {
	return m.Size()
}
func (m *PocCount) XXX_DiscardUnknown() {
	xxx_messageInfo_PocCount.DiscardUnknown(m)
}

var xxx_messageInfo_PocCount proto.InternalMessageInfo

func (m *PocCount) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PocCount) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PocCount) GetEntries() []*PocCountEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *PocCount) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type PocWeightCommit struct {
	Creator                  string          `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PocStageStartBlockHeight int64           `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Count                    uint32          `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	RootHash                 []byte          `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Weights                  []*MLNodeWeight `protobuf:"bytes,5,rep,name=weights,proto3" json:"weights,omitempty"`
	BlockHeight              int64           `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *PocWeightCommit) Reset()         { *m = PocWeightCommit{} }
func (m *PocWeightCommit) String() string { return proto.CompactTextString(m) }
func (*PocWeightCommit) ProtoMessage()    {}
func (*PocWeightCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{8}
}
func (m *PocWeightCommit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PocWeightCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PocWeightCommit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PocWeightCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PocWeightCommit.Merge(m, src)
}
func (m *PocWeightCommit) XXX_Size() int {
	return m.Size()
}
func (m *PocWeightCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_PocWeightCommit.DiscardUnknown(m)
}

var xxx_messageInfo_PocWeightCommit proto.InternalMessageInfo

func (m *PocWeightCommit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PocWeightCommit) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PocWeightCommit) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PocWeightCommit) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *PocWeightCommit) GetWeights() []*MLNodeWeight {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *PocWeightCommit) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type AgreedCount struct {
	Participant     string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	AgreedCount     uint32 `protobuf:"varint,2,opt,name=agreed_count,json=agreedCount,proto3" json:"agreed_count,omitempty"`
	TotalValidators int32  `protobuf:"varint,3,opt,name=total_validators,json=totalValidators,proto3" json:"total_validators,omitempty"`
	AgreeingCount   int32  `protobuf:"varint,4,opt,name=agreeing_count,json=agreeingCount,proto3" json:"agreeing_count,omitempty"`
}

func (m *AgreedCount) Reset()         { *m = AgreedCount{} }
func (m *AgreedCount) String() string { return proto.CompactTextString(m) }
func (*AgreedCount) ProtoMessage()    {}
func (*AgreedCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{9}
}
func (m *AgreedCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgreedCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgreedCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgreedCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreedCount.Merge(m, src)
}
func (m *AgreedCount) XXX_Size() int {
	return m.Size()
}
func (m *AgreedCount) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreedCount.DiscardUnknown(m)
}

var xxx_messageInfo_AgreedCount proto.InternalMessageInfo

func (m *AgreedCount) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *AgreedCount) GetAgreedCount() uint32 {
	if m != nil {
		return m.AgreedCount
	}
	return 0
}

func (m *AgreedCount) GetTotalValidators() int32 {
	if m != nil {
		return m.TotalValidators
	}
	return 0
}

func (m *AgreedCount) GetAgreeingCount() int32 {
	if m != nil {
		return m.AgreeingCount
	}
	return 0
}

func init() {
	proto.RegisterType((*PoCArtifactV2)(nil), "inference.inference.PoCArtifactV2")
	proto.RegisterType((*PoCValidationV2)(nil), "inference.inference.PoCValidationV2")
	proto.RegisterType((*PoCValidationPayloadV2)(nil), "inference.inference.PoCValidationPayloadV2")
	proto.RegisterType((*MLNodeWeight)(nil), "inference.inference.MLNodeWeight")
	proto.RegisterType((*PoCV2StoreCommit)(nil), "inference.inference.PoCV2StoreCommit")
	proto.RegisterType((*MLNodeWeightDistribution)(nil), "inference.inference.MLNodeWeightDistribution")
	proto.RegisterType((*PocCountEntry)(nil), "inference.inference.PocCountEntry")
	proto.RegisterType((*PocCount)(nil), "inference.inference.PocCount")
	proto.RegisterType((*PocWeightCommit)(nil), "inference.inference.PocWeightCommit")
	proto.RegisterType((*AgreedCount)(nil), "inference.inference.AgreedCount")
}

func init() { proto.RegisterFile("inference/inference/poc_v2.proto", fileDescriptor_02f1658865fe708f) }

var fileDescriptor_02f1658865fe708f = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcf, 0x6a, 0x1b, 0x3f,
	0x10, 0x8e, 0xec, 0xd8, 0x4e, 0xc6, 0xf6, 0x2f, 0xf9, 0x29, 0x21, 0x5d, 0x48, 0x6b, 0x9c, 0x85,
	0x82, 0x73, 0x71, 0xc0, 0xa5, 0xa7, 0xfe, 0x23, 0x71, 0x4b, 0x53, 0xe8, 0x1f, 0xb3, 0x01, 0x17,
	0x7a, 0x59, 0x64, 0xad, 0x62, 0x8b, 0x3a, 0xab, 0x45, 0x2b, 0xa7, 0xcd, 0x5b, 0xf4, 0x21, 0xfa,
	0x2a, 0x85, 0x1c, 0x73, 0xec, 0xb1, 0x24, 0xd0, 0x7b, 0x5f, 0xa0, 0x14, 0x49, 0x6b, 0x47, 0x6e,
	0x0c, 0x26, 0x29, 0xed, 0x65, 0xd1, 0x8c, 0x66, 0xbe, 0x99, 0xef, 0x1b, 0x69, 0x05, 0x75, 0x1e,
	0x1f, 0x32, 0xc9, 0x62, 0xca, 0x76, 0x2e, 0x57, 0x89, 0xa0, 0xe1, 0x71, 0xab, 0x99, 0x48, 0xa1,
	0x04, 0x5e, 0x9b, 0xf8, 0x9b, 0x93, 0x95, 0xff, 0x08, 0xaa, 0x1d, 0xd1, 0xde, 0x95, 0x8a, 0x1f,
	0x12, 0xaa, 0xba, 0x2d, 0xbc, 0x0e, 0x85, 0x58, 0xc4, 0x94, 0x79, 0xa8, 0x8e, 0x1a, 0x85, 0xc0,
	0x1a, 0x78, 0x03, 0x8a, 0xc7, 0x8c, 0x2a, 0x21, 0xbd, 0x5c, 0x1d, 0x35, 0x2a, 0x41, 0x66, 0xf9,
	0x3f, 0x10, 0xac, 0x74, 0x44, 0xbb, 0x4b, 0x86, 0x3c, 0x22, 0x8a, 0x8b, 0xb8, 0xdb, 0xc2, 0x3b,
	0xb0, 0x96, 0x10, 0xa9, 0x38, 0xe5, 0x09, 0x89, 0x55, 0x48, 0xa2, 0x48, 0xb2, 0x34, 0x35, 0x78,
	0xcb, 0x01, 0x76, 0xb6, 0x76, 0xed, 0x0e, 0xde, 0x83, 0x3b, 0xc7, 0x16, 0x40, 0xc8, 0x70, 0x56,
	0x6a, 0xce, 0xa4, 0x6e, 0x4e, 0x82, 0x3a, 0x57, 0x31, 0x1e, 0xc3, 0x6d, 0x4d, 0x36, 0x55, 0xa4,
	0xcf, 0xf4, 0x57, 0xaa, 0xb0, 0x37, 0x14, 0xf4, 0x7d, 0x38, 0x60, 0xbc, 0x3f, 0x50, 0x5e, 0xbe,
	0x8e, 0x1a, 0xf9, 0xc0, 0x4b, 0x04, 0x3d, 0xd0, 0x21, 0x07, 0x3a, 0x62, 0x4f, 0x07, 0xec, 0x9b,
	0x7d, 0xbc, 0x0d, 0xab, 0x19, 0x3c, 0x8b, 0xc2, 0x0f, 0x36, 0x67, 0xd1, 0xe4, 0xac, 0x4c, 0xfc,
	0x6f, 0x8d, 0xdb, 0x57, 0xb0, 0x31, 0x45, 0xb9, 0x43, 0x4e, 0x86, 0x82, 0x44, 0x37, 0x61, 0x3e,
	0xab, 0x6a, 0x6e, 0x76, 0xd5, 0x27, 0x50, 0x79, 0xf5, 0xf2, 0xb5, 0x88, 0x98, 0xb5, 0xf1, 0x2d,
	0x28, 0xc5, 0x22, 0x62, 0x21, 0x8f, 0x32, 0xfc, 0xa2, 0x36, 0x5f, 0x44, 0x7a, 0x54, 0x0e, 0x52,
	0x35, 0xc8, 0x2c, 0xff, 0x3b, 0x82, 0x55, 0xdd, 0x77, 0xeb, 0x40, 0x09, 0xc9, 0xda, 0xe2, 0xe8,
	0x88, 0xab, 0xeb, 0x77, 0x3c, 0x4f, 0xe7, 0xdc, 0x1c, 0x9d, 0xd7, 0xa1, 0x40, 0xc5, 0x28, 0xb6,
	0x03, 0xa9, 0x06, 0xd6, 0xc0, 0x9b, 0xb0, 0x2c, 0x85, 0x50, 0xe1, 0x80, 0xa4, 0x03, 0x23, 0x7b,
	0x25, 0x58, 0xd2, 0x8e, 0x7d, 0x92, 0x0e, 0x70, 0x13, 0xd6, 0xa8, 0xe9, 0x76, 0xba, 0x52, 0xc1,
	0x54, 0xfa, 0xdf, 0x6e, 0x39, 0x25, 0xfc, 0x53, 0x04, 0x9e, 0x2b, 0xd5, 0x53, 0x9e, 0x2a, 0xc9,
	0x7b, 0x23, 0x3d, 0xab, 0x7f, 0x4f, 0xf8, 0x01, 0x94, 0xec, 0x00, 0x52, 0x2f, 0x5f, 0xcf, 0x37,
	0xca, 0xad, 0xad, 0xe6, 0x8c, 0x7b, 0xd8, 0x74, 0x1b, 0x0e, 0xc6, 0x19, 0xfe, 0x73, 0x7d, 0x3b,
	0x69, 0x5b, 0x6b, 0xf4, 0x2c, 0x56, 0xf2, 0x04, 0xd7, 0xa1, 0xec, 0xf4, 0x98, 0xb5, 0xed, 0xba,
	0x2e, 0x05, 0xce, 0x39, 0x02, 0xfb, 0x5f, 0x10, 0x2c, 0x8d, 0x91, 0xb0, 0x07, 0x25, 0x2a, 0x99,
	0xbe, 0x48, 0x19, 0xc0, 0xd8, 0xfc, 0x63, 0xb2, 0x0f, 0xa1, 0xc4, 0x62, 0x25, 0x39, 0x1b, 0x93,
	0xf5, 0x67, 0x92, 0x9d, 0xe2, 0x14, 0x8c, 0x53, 0xf0, 0x16, 0x54, 0xa6, 0xaa, 0xd9, 0xfb, 0x57,
	0xee, 0x39, 0xb3, 0xfd, 0x69, 0xfe, 0x37, 0xd4, 0xea, 0x94, 0x9d, 0xe1, 0xbf, 0x47, 0xe7, 0x06,
	0x87, 0xd5, 0x19, 0x77, 0xe1, 0xba, 0xe3, 0xbe, 0x22, 0x40, 0xf1, 0xaa, 0x00, 0x9f, 0x11, 0x94,
	0x77, 0xfb, 0x92, 0xb1, 0xc8, 0xce, 0x72, 0xfe, 0x81, 0xd8, 0x82, 0x0a, 0x31, 0x09, 0xa1, 0x7b,
	0x2e, 0xca, 0xc4, 0x01, 0xd9, 0x86, 0x55, 0x25, 0x14, 0x19, 0x86, 0x93, 0x3f, 0x6c, 0x6a, 0x28,
	0x17, 0x82, 0x15, 0xe3, 0xef, 0x4e, 0xdc, 0xf8, 0x2e, 0xfc, 0x67, 0x32, 0x79, 0xdc, 0xcf, 0xf0,
	0x16, 0x4d, 0x60, 0x75, 0xec, 0x35, 0x88, 0x7b, 0x6f, 0x4e, 0xcf, 0x6b, 0xe8, 0xec, 0xbc, 0x86,
	0xbe, 0x9d, 0xd7, 0xd0, 0xa7, 0x8b, 0xda, 0xc2, 0xd9, 0x45, 0x6d, 0xe1, 0xeb, 0x45, 0x6d, 0xe1,
	0xdd, 0xfd, 0x3e, 0x57, 0x83, 0x51, 0xaf, 0x49, 0xc5, 0xd1, 0x4e, 0x22, 0x45, 0x34, 0xa2, 0x2a,
	0xa5, 0xfc, 0xb7, 0x77, 0xeb, 0xa3, 0xb3, 0x56, 0x27, 0x09, 0x4b, 0x7b, 0x45, 0xf3, 0x86, 0xdd,
	0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x69, 0x6d, 0xd7, 0xe7, 0x06, 0x00, 0x00,
}

func (m *PoCArtifactV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCArtifactV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCArtifactV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vector) > 0 {
		i -= len(m.Vector)
		copy(dAtA[i:], m.Vector)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Vector)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoCValidationV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatedWeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.ValidatedWeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorParticipantAddress) > 0 {
		i -= len(m.ValidatorParticipantAddress)
		copy(dAtA[i:], m.ValidatorParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ValidatorParticipantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCValidationPayloadV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationPayloadV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationPayloadV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatedWeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.ValidatedWeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MLNodeWeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MLNodeWeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MLNodeWeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Weight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCV2StoreCommit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCV2StoreCommit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCV2StoreCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommitBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.CommitBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Count != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x18
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MLNodeWeightDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MLNodeWeightDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MLNodeWeightDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Weights) > 0 {
		for iNdEx := len(m.Weights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Weights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PocCountEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PocCountEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PocCountEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PocCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PocCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PocCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PocWeightCommit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PocWeightCommit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PocWeightCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Weights) > 0 {
		for iNdEx := len(m.Weights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Weights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Count != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x18
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AgreedCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgreedCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgreedCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AgreeingCount != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.AgreeingCount))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalValidators != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.TotalValidators))
		i--
		dAtA[i] = 0x18
	}
	if m.AgreedCount != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.AgreedCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPocV2(dAtA []byte, offset int, v uint64) int {
	offset -= sovPocV2(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoCArtifactV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovPocV2(uint64(m.Nonce))
	}
	l = len(m.Vector)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *PoCValidationV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	l = len(m.ValidatorParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if m.ValidatedWeight != 0 {
		n += 1 + sovPocV2(uint64(m.ValidatedWeight))
	}
	return n
}

func (m *PoCValidationPayloadV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.ValidatedWeight != 0 {
		n += 1 + sovPocV2(uint64(m.ValidatedWeight))
	}
	return n
}

func (m *MLNodeWeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovPocV2(uint64(m.Weight))
	}
	return n
}

func (m *PoCV2StoreCommit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if m.Count != 0 {
		n += 1 + sovPocV2(uint64(m.Count))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.CommitBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.CommitBlockHeight))
	}
	return n
}

func (m *MLNodeWeightDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if len(m.Weights) > 0 {
		for _, e := range m.Weights {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	return n
}

func (m *PocCountEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovPocV2(uint64(m.Count))
	}
	return n
}

func (m *PocCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.BlockHeight))
	}
	return n
}

func (m *PocWeightCommit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if m.Count != 0 {
		n += 1 + sovPocV2(uint64(m.Count))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if len(m.Weights) > 0 {
		for _, e := range m.Weights {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.BlockHeight))
	}
	return n
}

func (m *AgreedCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.AgreedCount != 0 {
		n += 1 + sovPocV2(uint64(m.AgreedCount))
	}
	if m.TotalValidators != 0 {
		n += 1 + sovPocV2(uint64(m.TotalValidators))
	}
	if m.AgreeingCount != 0 {
		n += 1 + sovPocV2(uint64(m.AgreeingCount))
	}
	return n
}

func sovPocV2(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPocV2(x uint64) (n int) {
	return sovPocV2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoCArtifactV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCArtifactV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCArtifactV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vector", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vector = append(m.Vector[:0], dAtA[iNdEx:postIndex]...)
			if m.Vector == nil {
				m.Vector = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCValidationV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedWeight", wireType)
			}
			m.ValidatedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCValidationPayloadV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationPayloadV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationPayloadV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedWeight", wireType)
			}
			m.ValidatedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MLNodeWeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MLNodeWeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MLNodeWeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCV2StoreCommit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCV2StoreCommit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCV2StoreCommit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = append(m.RootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RootHash == nil {
				m.RootHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitBlockHeight", wireType)
			}
			m.CommitBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MLNodeWeightDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MLNodeWeightDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MLNodeWeightDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = append(m.Weights, &MLNodeWeight{})
			if err := m.Weights[len(m.Weights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PocCountEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PocCountEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PocCountEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PocCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PocCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PocCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &PocCountEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PocWeightCommit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PocWeightCommit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PocWeightCommit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = append(m.RootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RootHash == nil {
				m.RootHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = append(m.Weights, &MLNodeWeight{})
			if err := m.Weights[len(m.Weights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AgreedCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgreedCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgreedCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreedCount", wireType)
			}
			m.AgreedCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgreedCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValidators", wireType)
			}
			m.TotalValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalValidators |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreeingCount", wireType)
			}
			m.AgreeingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgreeingCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPocV2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPocV2
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPocV2
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPocV2
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPocV2        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPocV2          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPocV2 = fmt.Errorf("proto: unexpected end of group")
)
