// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/poc_v2.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoCArtifactV2 represents a single artifact from PoC v2 generation.
// Used for local off-chain storage and proof verification.
type PoCArtifactV2 struct {
	Nonce  int32  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Vector []byte `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
}

func (m *PoCArtifactV2) Reset()         { *m = PoCArtifactV2{} }
func (m *PoCArtifactV2) String() string { return proto.CompactTextString(m) }
func (*PoCArtifactV2) ProtoMessage()    {}
func (*PoCArtifactV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{0}
}
func (m *PoCArtifactV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCArtifactV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCArtifactV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCArtifactV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCArtifactV2.Merge(m, src)
}
func (m *PoCArtifactV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCArtifactV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCArtifactV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCArtifactV2 proto.InternalMessageInfo

func (m *PoCArtifactV2) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *PoCArtifactV2) GetVector() []byte {
	if m != nil {
		return m.Vector
	}
	return nil
}

// PoCValidationV2 represents a validator's attestation of a participant's PoC work.
// validated_weight: -1 = reject/fraud, >0 = accept
type PoCValidationV2 struct {
	ParticipantAddress          string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	ValidatorParticipantAddress string `protobuf:"bytes,2,opt,name=validator_participant_address,json=validatorParticipantAddress,proto3" json:"validator_participant_address,omitempty"`
	PocStageStartBlockHeight    int64  `protobuf:"varint,3,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	ModelId                     string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ValidatedWeight             int64  `protobuf:"varint,5,opt,name=validated_weight,json=validatedWeight,proto3" json:"validated_weight,omitempty"`
}

func (m *PoCValidationV2) Reset()         { *m = PoCValidationV2{} }
func (m *PoCValidationV2) String() string { return proto.CompactTextString(m) }
func (*PoCValidationV2) ProtoMessage()    {}
func (*PoCValidationV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{1}
}
func (m *PoCValidationV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationV2.Merge(m, src)
}
func (m *PoCValidationV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationV2 proto.InternalMessageInfo

func (m *PoCValidationV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetValidatorParticipantAddress() string {
	if m != nil {
		return m.ValidatorParticipantAddress
	}
	return ""
}

func (m *PoCValidationV2) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCValidationV2) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *PoCValidationV2) GetValidatedWeight() int64 {
	if m != nil {
		return m.ValidatedWeight
	}
	return 0
}

// PoCValidationEntryV2 is the message payload for validation submission.
// Height is at message level, validator derived from signer.
type PoCValidationEntryV2 struct {
	ParticipantAddress string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	ModelId            string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ValidatedWeight    int64  `protobuf:"varint,3,opt,name=validated_weight,json=validatedWeight,proto3" json:"validated_weight,omitempty"`
}

func (m *PoCValidationEntryV2) Reset()         { *m = PoCValidationEntryV2{} }
func (m *PoCValidationEntryV2) String() string { return proto.CompactTextString(m) }
func (*PoCValidationEntryV2) ProtoMessage()    {}
func (*PoCValidationEntryV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{2}
}
func (m *PoCValidationEntryV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCValidationEntryV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCValidationEntryV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCValidationEntryV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCValidationEntryV2.Merge(m, src)
}
func (m *PoCValidationEntryV2) XXX_Size() int {
	return m.Size()
}
func (m *PoCValidationEntryV2) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCValidationEntryV2.DiscardUnknown(m)
}

var xxx_messageInfo_PoCValidationEntryV2 proto.InternalMessageInfo

func (m *PoCValidationEntryV2) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCValidationEntryV2) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *PoCValidationEntryV2) GetValidatedWeight() int64 {
	if m != nil {
		return m.ValidatedWeight
	}
	return 0
}

// MLNodeWeight represents artifact count attributed to a single node.
type MLNodeWeight struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Weight uint32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (m *MLNodeWeight) Reset()         { *m = MLNodeWeight{} }
func (m *MLNodeWeight) String() string { return proto.CompactTextString(m) }
func (*MLNodeWeight) ProtoMessage()    {}
func (*MLNodeWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{3}
}
func (m *MLNodeWeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MLNodeWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MLNodeWeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MLNodeWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLNodeWeight.Merge(m, src)
}
func (m *MLNodeWeight) XXX_Size() int {
	return m.Size()
}
func (m *MLNodeWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_MLNodeWeight.DiscardUnknown(m)
}

var xxx_messageInfo_MLNodeWeight proto.InternalMessageInfo

func (m *MLNodeWeight) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MLNodeWeight) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// PoCV2StoreCommit stores the off-chain artifact store state.
type PoCV2StoreCommit struct {
	ParticipantAddress       string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	PocStageStartBlockHeight int64  `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Count                    uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	RootHash                 []byte `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	CommitBlockHeight        int64  `protobuf:"varint,5,opt,name=commit_block_height,json=commitBlockHeight,proto3" json:"commit_block_height,omitempty"`
	ModelId                  string `protobuf:"bytes,6,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
}

func (m *PoCV2StoreCommit) Reset()         { *m = PoCV2StoreCommit{} }
func (m *PoCV2StoreCommit) String() string { return proto.CompactTextString(m) }
func (*PoCV2StoreCommit) ProtoMessage()    {}
func (*PoCV2StoreCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{4}
}
func (m *PoCV2StoreCommit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCV2StoreCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCV2StoreCommit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCV2StoreCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCV2StoreCommit.Merge(m, src)
}
func (m *PoCV2StoreCommit) XXX_Size() int {
	return m.Size()
}
func (m *PoCV2StoreCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCV2StoreCommit.DiscardUnknown(m)
}

var xxx_messageInfo_PoCV2StoreCommit proto.InternalMessageInfo

func (m *PoCV2StoreCommit) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *PoCV2StoreCommit) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *PoCV2StoreCommit) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PoCV2StoreCommit) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *PoCV2StoreCommit) GetCommitBlockHeight() int64 {
	if m != nil {
		return m.CommitBlockHeight
	}
	return 0
}

func (m *PoCV2StoreCommit) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

type PoCV2CommitEntry struct {
	ModelId  string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Count    uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	RootHash []byte `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
}

func (m *PoCV2CommitEntry) Reset()         { *m = PoCV2CommitEntry{} }
func (m *PoCV2CommitEntry) String() string { return proto.CompactTextString(m) }
func (*PoCV2CommitEntry) ProtoMessage()    {}
func (*PoCV2CommitEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{5}
}
func (m *PoCV2CommitEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoCV2CommitEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoCV2CommitEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoCV2CommitEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoCV2CommitEntry.Merge(m, src)
}
func (m *PoCV2CommitEntry) XXX_Size() int {
	return m.Size()
}
func (m *PoCV2CommitEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PoCV2CommitEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PoCV2CommitEntry proto.InternalMessageInfo

func (m *PoCV2CommitEntry) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *PoCV2CommitEntry) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PoCV2CommitEntry) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

// MLNodeWeightDistribution stores per-node weight distribution.
type MLNodeWeightDistribution struct {
	ParticipantAddress       string          `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	PocStageStartBlockHeight int64           `protobuf:"varint,2,opt,name=poc_stage_start_block_height,json=pocStageStartBlockHeight,proto3" json:"poc_stage_start_block_height,omitempty"`
	Weights                  []*MLNodeWeight `protobuf:"bytes,3,rep,name=weights,proto3" json:"weights,omitempty"`
	ModelId                  string          `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
}

func (m *MLNodeWeightDistribution) Reset()         { *m = MLNodeWeightDistribution{} }
func (m *MLNodeWeightDistribution) String() string { return proto.CompactTextString(m) }
func (*MLNodeWeightDistribution) ProtoMessage()    {}
func (*MLNodeWeightDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{6}
}
func (m *MLNodeWeightDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MLNodeWeightDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MLNodeWeightDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MLNodeWeightDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLNodeWeightDistribution.Merge(m, src)
}
func (m *MLNodeWeightDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MLNodeWeightDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MLNodeWeightDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MLNodeWeightDistribution proto.InternalMessageInfo

func (m *MLNodeWeightDistribution) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

func (m *MLNodeWeightDistribution) GetPocStageStartBlockHeight() int64 {
	if m != nil {
		return m.PocStageStartBlockHeight
	}
	return 0
}

func (m *MLNodeWeightDistribution) GetWeights() []*MLNodeWeight {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *MLNodeWeightDistribution) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

type MLNodeDistributionEntry struct {
	ModelId string          `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Weights []*MLNodeWeight `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
}

func (m *MLNodeDistributionEntry) Reset()         { *m = MLNodeDistributionEntry{} }
func (m *MLNodeDistributionEntry) String() string { return proto.CompactTextString(m) }
func (*MLNodeDistributionEntry) ProtoMessage()    {}
func (*MLNodeDistributionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f1658865fe708f, []int{7}
}
func (m *MLNodeDistributionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MLNodeDistributionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MLNodeDistributionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MLNodeDistributionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MLNodeDistributionEntry.Merge(m, src)
}
func (m *MLNodeDistributionEntry) XXX_Size() int {
	return m.Size()
}
func (m *MLNodeDistributionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MLNodeDistributionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MLNodeDistributionEntry proto.InternalMessageInfo

func (m *MLNodeDistributionEntry) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *MLNodeDistributionEntry) GetWeights() []*MLNodeWeight {
	if m != nil {
		return m.Weights
	}
	return nil
}

func init() {
	proto.RegisterType((*PoCArtifactV2)(nil), "inference.inference.PoCArtifactV2")
	proto.RegisterType((*PoCValidationV2)(nil), "inference.inference.PoCValidationV2")
	proto.RegisterType((*PoCValidationEntryV2)(nil), "inference.inference.PoCValidationEntryV2")
	proto.RegisterType((*MLNodeWeight)(nil), "inference.inference.MLNodeWeight")
	proto.RegisterType((*PoCV2StoreCommit)(nil), "inference.inference.PoCV2StoreCommit")
	proto.RegisterType((*PoCV2CommitEntry)(nil), "inference.inference.PoCV2CommitEntry")
	proto.RegisterType((*MLNodeWeightDistribution)(nil), "inference.inference.MLNodeWeightDistribution")
	proto.RegisterType((*MLNodeDistributionEntry)(nil), "inference.inference.MLNodeDistributionEntry")
}

func init() { proto.RegisterFile("inference/inference/poc_v2.proto", fileDescriptor_02f1658865fe708f) }

var fileDescriptor_02f1658865fe708f = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xa6, 0xad, 0xc0, 0xee, 0x08, 0xd9, 0x75, 0x20, 0x6e, 0xcd, 0x6a, 0x83, 0x3d, 0xe1, 0xa5,
	0x24, 0x18, 0x4f, 0x46, 0xcd, 0x82, 0x26, 0xbb, 0x89, 0x3f, 0x48, 0x49, 0x30, 0xf1, 0x52, 0xcb,
	0xcc, 0x2c, 0x9d, 0x08, 0x9d, 0x3a, 0x1d, 0xd0, 0x3d, 0x7a, 0xd7, 0xc4, 0x3f, 0xcb, 0xe3, 0x1e,
	0x3d, 0x1a, 0xf8, 0x47, 0xcc, 0xcc, 0x60, 0x6d, 0x95, 0x95, 0xac, 0x87, 0xbd, 0x90, 0xf9, 0xe6,
	0xbd, 0xf7, 0xbd, 0xef, 0xbd, 0x8f, 0x0e, 0x68, 0xd1, 0xf8, 0x94, 0x70, 0x12, 0x23, 0xd2, 0xf9,
	0x7d, 0x4a, 0x18, 0x0a, 0x16, 0x5d, 0x2f, 0xe1, 0x4c, 0x30, 0xd8, 0xc8, 0xee, 0xbd, 0xec, 0xe4,
	0x3e, 0x02, 0xf5, 0x01, 0xeb, 0x1f, 0x71, 0x41, 0x4f, 0x43, 0x24, 0x46, 0x5d, 0xd8, 0x04, 0xe5,
	0x98, 0xc5, 0x88, 0xd8, 0x46, 0xcb, 0x68, 0x97, 0x7d, 0x0d, 0xe0, 0x4d, 0x50, 0x59, 0x10, 0x24,
	0x18, 0xb7, 0xcd, 0x96, 0xd1, 0xae, 0xf9, 0x6b, 0xe4, 0x7e, 0x36, 0xc1, 0xde, 0x80, 0xf5, 0x47,
	0xe1, 0x94, 0xe2, 0x50, 0x50, 0x16, 0x8f, 0xba, 0xb0, 0x03, 0x1a, 0x49, 0xc8, 0x05, 0x45, 0x34,
	0x09, 0x63, 0x11, 0x84, 0x18, 0x73, 0x92, 0xa6, 0x8a, 0x6f, 0xd7, 0x87, 0xb9, 0xd0, 0x91, 0x8e,
	0xc0, 0x1e, 0xb8, 0xb3, 0xd0, 0x04, 0x8c, 0x07, 0x9b, 0x4a, 0x4d, 0x55, 0x7a, 0x98, 0x25, 0x0d,
	0xfe, 0xe6, 0x78, 0x0c, 0x6e, 0xcb, 0x61, 0x53, 0x11, 0x4e, 0x88, 0xfc, 0xe5, 0x22, 0x18, 0x4f,
	0x19, 0x7a, 0x17, 0x44, 0x84, 0x4e, 0x22, 0x61, 0x5b, 0x2d, 0xa3, 0x6d, 0xf9, 0x76, 0xc2, 0xd0,
	0x50, 0xa6, 0x0c, 0x65, 0x46, 0x4f, 0x26, 0x1c, 0xab, 0x38, 0xbc, 0x05, 0x76, 0x66, 0x0c, 0x93,
	0x69, 0x40, 0xb1, 0x7d, 0x4d, 0xb5, 0xab, 0x2a, 0x7c, 0x82, 0xe1, 0x3d, 0xb0, 0xbf, 0xee, 0x4c,
	0x70, 0xf0, 0x41, 0xd3, 0x95, 0x15, 0xdd, 0x5e, 0x76, 0xff, 0x5a, 0x5d, 0xbb, 0x5f, 0x0c, 0xd0,
	0x2c, 0xac, 0xe3, 0x59, 0x2c, 0xf8, 0xd9, 0xff, 0xec, 0x24, 0xaf, 0xc7, 0xdc, 0xae, 0xc7, 0xda,
	0xac, 0xe7, 0x09, 0xa8, 0xbd, 0x78, 0xfe, 0x92, 0x61, 0xa2, 0x31, 0x3c, 0x00, 0xd5, 0x98, 0x61,
	0x22, 0x49, 0x75, 0xeb, 0x8a, 0x84, 0x27, 0x58, 0xfa, 0xbb, 0x66, 0x92, 0xcd, 0xea, 0xfe, 0x1a,
	0xb9, 0x9f, 0x4c, 0xb0, 0x2f, 0x07, 0xea, 0x0e, 0x05, 0xe3, 0xa4, 0xcf, 0x66, 0x33, 0x2a, 0x2e,
	0x3f, 0xcc, 0x36, 0x73, 0xcc, 0x2d, 0xe6, 0x34, 0x41, 0x19, 0xb1, 0x79, 0xac, 0xc7, 0xac, 0xfb,
	0x1a, 0xc0, 0x43, 0xb0, 0xcb, 0x19, 0x13, 0x41, 0x14, 0xa6, 0x91, 0xf2, 0xac, 0xe6, 0xef, 0xc8,
	0x8b, 0xe3, 0x30, 0x8d, 0xa0, 0x07, 0x1a, 0x48, 0xa9, 0x2d, 0x76, 0xd2, 0xbe, 0xdd, 0xd0, 0xa1,
	0x8b, 0xfc, 0xaf, 0x14, 0xf6, 0xed, 0xbe, 0x5d, 0xaf, 0x40, 0x4f, 0xaf, 0x1c, 0x2d, 0xa4, 0x1b,
	0x45, 0x7b, 0x32, 0xb1, 0xe6, 0x85, 0x62, 0xad, 0xa2, 0x58, 0x77, 0x65, 0x00, 0x3b, 0xef, 0xd3,
	0x53, 0x9a, 0x0a, 0x4e, 0xc7, 0x73, 0xf9, 0x0f, 0xba, 0xfa, 0x6d, 0x3f, 0x04, 0x55, 0xed, 0x7e,
	0x6a, 0x5b, 0x2d, 0xab, 0x7d, 0xbd, 0x7b, 0xd7, 0xdb, 0xf0, 0x72, 0x78, 0x79, 0xc1, 0xfe, 0xaf,
	0x8a, 0x7f, 0x7c, 0x47, 0xee, 0x7b, 0x70, 0xa0, 0x6b, 0xf2, 0xe3, 0x6d, 0x5d, 0x67, 0x4e, 0x8d,
	0x79, 0x59, 0x35, 0xbd, 0x57, 0xdf, 0x96, 0x8e, 0x71, 0xbe, 0x74, 0x8c, 0x1f, 0x4b, 0xc7, 0xf8,
	0xba, 0x72, 0x4a, 0xe7, 0x2b, 0xa7, 0xf4, 0x7d, 0xe5, 0x94, 0xde, 0x3c, 0x98, 0x50, 0x11, 0xcd,
	0xc7, 0x1e, 0x62, 0xb3, 0x4e, 0xc2, 0x19, 0x9e, 0x23, 0x91, 0x22, 0xfa, 0xc7, 0xf3, 0xf9, 0x31,
	0x77, 0x16, 0x67, 0x09, 0x49, 0xc7, 0x15, 0xf5, 0x94, 0xde, 0xff, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x21, 0xc7, 0x0d, 0x50, 0x6e, 0x05, 0x00, 0x00,
}

func (m *PoCArtifactV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCArtifactV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCArtifactV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vector) > 0 {
		i -= len(m.Vector)
		copy(dAtA[i:], m.Vector)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.Vector)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoCValidationV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatedWeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.ValidatedWeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x22
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorParticipantAddress) > 0 {
		i -= len(m.ValidatorParticipantAddress)
		copy(dAtA[i:], m.ValidatorParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ValidatorParticipantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCValidationEntryV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCValidationEntryV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCValidationEntryV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatedWeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.ValidatedWeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MLNodeWeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MLNodeWeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MLNodeWeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Weight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCV2StoreCommit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCV2StoreCommit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCV2StoreCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x32
	}
	if m.CommitBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.CommitBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Count != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x18
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoCV2CommitEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoCV2CommitEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoCV2CommitEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Count != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MLNodeWeightDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MLNodeWeightDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MLNodeWeightDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Weights) > 0 {
		for iNdEx := len(m.Weights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Weights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PocStageStartBlockHeight != 0 {
		i = encodeVarintPocV2(dAtA, i, uint64(m.PocStageStartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MLNodeDistributionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MLNodeDistributionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MLNodeDistributionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Weights) > 0 {
		for iNdEx := len(m.Weights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Weights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocV2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPocV2(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPocV2(dAtA []byte, offset int, v uint64) int {
	offset -= sovPocV2(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoCArtifactV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovPocV2(uint64(m.Nonce))
	}
	l = len(m.Vector)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *PoCValidationV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	l = len(m.ValidatorParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.ValidatedWeight != 0 {
		n += 1 + sovPocV2(uint64(m.ValidatedWeight))
	}
	return n
}

func (m *PoCValidationEntryV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.ValidatedWeight != 0 {
		n += 1 + sovPocV2(uint64(m.ValidatedWeight))
	}
	return n
}

func (m *MLNodeWeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovPocV2(uint64(m.Weight))
	}
	return n
}

func (m *PoCV2StoreCommit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if m.Count != 0 {
		n += 1 + sovPocV2(uint64(m.Count))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.CommitBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.CommitBlockHeight))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *PoCV2CommitEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovPocV2(uint64(m.Count))
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *MLNodeWeightDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if m.PocStageStartBlockHeight != 0 {
		n += 1 + sovPocV2(uint64(m.PocStageStartBlockHeight))
	}
	if len(m.Weights) > 0 {
		for _, e := range m.Weights {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	return n
}

func (m *MLNodeDistributionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPocV2(uint64(l))
	}
	if len(m.Weights) > 0 {
		for _, e := range m.Weights {
			l = e.Size()
			n += 1 + l + sovPocV2(uint64(l))
		}
	}
	return n
}

func sovPocV2(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPocV2(x uint64) (n int) {
	return sovPocV2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoCArtifactV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCArtifactV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCArtifactV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vector", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vector = append(m.Vector[:0], dAtA[iNdEx:postIndex]...)
			if m.Vector == nil {
				m.Vector = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCValidationV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedWeight", wireType)
			}
			m.ValidatedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCValidationEntryV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCValidationEntryV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCValidationEntryV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedWeight", wireType)
			}
			m.ValidatedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MLNodeWeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MLNodeWeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MLNodeWeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCV2StoreCommit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCV2StoreCommit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCV2StoreCommit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = append(m.RootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RootHash == nil {
				m.RootHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitBlockHeight", wireType)
			}
			m.CommitBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoCV2CommitEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoCV2CommitEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoCV2CommitEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = append(m.RootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RootHash == nil {
				m.RootHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MLNodeWeightDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MLNodeWeightDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MLNodeWeightDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStageStartBlockHeight", wireType)
			}
			m.PocStageStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStageStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = append(m.Weights, &MLNodeWeight{})
			if err := m.Weights[len(m.Weights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MLNodeDistributionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MLNodeDistributionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MLNodeDistributionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocV2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocV2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = append(m.Weights, &MLNodeWeight{})
			if err := m.Weights[len(m.Weights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocV2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPocV2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPocV2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPocV2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocV2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPocV2
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPocV2
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPocV2
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPocV2        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPocV2          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPocV2 = fmt.Errorf("proto: unexpected end of group")
)
