// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/subnet_escrow.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubnetEscrow struct {
	Id         uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator    string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount     uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Slots      []string `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	EpochIndex uint64   `protobuf:"varint,5,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	AppHash    string   `protobuf:"bytes,6,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	Settled    bool     `protobuf:"varint,7,opt,name=settled,proto3" json:"settled,omitempty"`
	TokenPrice uint64   `protobuf:"varint,8,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
}

func (m *SubnetEscrow) Reset()         { *m = SubnetEscrow{} }
func (m *SubnetEscrow) String() string { return proto.CompactTextString(m) }
func (*SubnetEscrow) ProtoMessage()    {}
func (*SubnetEscrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9df301d9fc443f7, []int{0}
}
func (m *SubnetEscrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetEscrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetEscrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetEscrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetEscrow.Merge(m, src)
}
func (m *SubnetEscrow) XXX_Size() int {
	return m.Size()
}
func (m *SubnetEscrow) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetEscrow.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetEscrow proto.InternalMessageInfo

func (m *SubnetEscrow) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubnetEscrow) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SubnetEscrow) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SubnetEscrow) GetSlots() []string {
	if m != nil {
		return m.Slots
	}
	return nil
}

func (m *SubnetEscrow) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *SubnetEscrow) GetAppHash() string {
	if m != nil {
		return m.AppHash
	}
	return ""
}

func (m *SubnetEscrow) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

func (m *SubnetEscrow) GetTokenPrice() uint64 {
	if m != nil {
		return m.TokenPrice
	}
	return 0
}

type SubnetHostEpochStats struct {
	Participant          string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	EpochIndex           uint64 `protobuf:"varint,2,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	Missed               uint32 `protobuf:"varint,3,opt,name=missed,proto3" json:"missed,omitempty"`
	Invalid              uint32 `protobuf:"varint,4,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Cost                 uint64 `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	RequiredValidations  uint32 `protobuf:"varint,6,opt,name=required_validations,json=requiredValidations,proto3" json:"required_validations,omitempty"`
	CompletedValidations uint32 `protobuf:"varint,7,opt,name=completed_validations,json=completedValidations,proto3" json:"completed_validations,omitempty"`
	EscrowCount          uint32 `protobuf:"varint,8,opt,name=escrow_count,json=escrowCount,proto3" json:"escrow_count,omitempty"`
	InferenceCount       uint32 `protobuf:"varint,9,opt,name=inference_count,json=inferenceCount,proto3" json:"inference_count,omitempty"`
	Validated            uint32 `protobuf:"varint,10,opt,name=validated,proto3" json:"validated,omitempty"`
}

func (m *SubnetHostEpochStats) Reset()         { *m = SubnetHostEpochStats{} }
func (m *SubnetHostEpochStats) String() string { return proto.CompactTextString(m) }
func (*SubnetHostEpochStats) ProtoMessage()    {}
func (*SubnetHostEpochStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9df301d9fc443f7, []int{1}
}
func (m *SubnetHostEpochStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetHostEpochStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetHostEpochStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetHostEpochStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetHostEpochStats.Merge(m, src)
}
func (m *SubnetHostEpochStats) XXX_Size() int {
	return m.Size()
}
func (m *SubnetHostEpochStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetHostEpochStats.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetHostEpochStats proto.InternalMessageInfo

func (m *SubnetHostEpochStats) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *SubnetHostEpochStats) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *SubnetHostEpochStats) GetMissed() uint32 {
	if m != nil {
		return m.Missed
	}
	return 0
}

func (m *SubnetHostEpochStats) GetInvalid() uint32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *SubnetHostEpochStats) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *SubnetHostEpochStats) GetRequiredValidations() uint32 {
	if m != nil {
		return m.RequiredValidations
	}
	return 0
}

func (m *SubnetHostEpochStats) GetCompletedValidations() uint32 {
	if m != nil {
		return m.CompletedValidations
	}
	return 0
}

func (m *SubnetHostEpochStats) GetEscrowCount() uint32 {
	if m != nil {
		return m.EscrowCount
	}
	return 0
}

func (m *SubnetHostEpochStats) GetInferenceCount() uint32 {
	if m != nil {
		return m.InferenceCount
	}
	return 0
}

func (m *SubnetHostEpochStats) GetValidated() uint32 {
	if m != nil {
		return m.Validated
	}
	return 0
}

type SubnetSettlementHostStats struct {
	SlotId               uint32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Missed               uint32 `protobuf:"varint,2,opt,name=missed,proto3" json:"missed,omitempty"`
	Invalid              uint32 `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Cost                 uint64 `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	RequiredValidations  uint32 `protobuf:"varint,5,opt,name=required_validations,json=requiredValidations,proto3" json:"required_validations,omitempty"`
	CompletedValidations uint32 `protobuf:"varint,6,opt,name=completed_validations,json=completedValidations,proto3" json:"completed_validations,omitempty"`
	InferenceCount       uint32 `protobuf:"varint,7,opt,name=inference_count,json=inferenceCount,proto3" json:"inference_count,omitempty"`
	Validated            uint32 `protobuf:"varint,8,opt,name=validated,proto3" json:"validated,omitempty"`
}

func (m *SubnetSettlementHostStats) Reset()         { *m = SubnetSettlementHostStats{} }
func (m *SubnetSettlementHostStats) String() string { return proto.CompactTextString(m) }
func (*SubnetSettlementHostStats) ProtoMessage()    {}
func (*SubnetSettlementHostStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9df301d9fc443f7, []int{2}
}
func (m *SubnetSettlementHostStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetSettlementHostStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetSettlementHostStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetSettlementHostStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetSettlementHostStats.Merge(m, src)
}
func (m *SubnetSettlementHostStats) XXX_Size() int {
	return m.Size()
}
func (m *SubnetSettlementHostStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetSettlementHostStats.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetSettlementHostStats proto.InternalMessageInfo

func (m *SubnetSettlementHostStats) GetSlotId() uint32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetMissed() uint32 {
	if m != nil {
		return m.Missed
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetInvalid() uint32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetRequiredValidations() uint32 {
	if m != nil {
		return m.RequiredValidations
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetCompletedValidations() uint32 {
	if m != nil {
		return m.CompletedValidations
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetInferenceCount() uint32 {
	if m != nil {
		return m.InferenceCount
	}
	return 0
}

func (m *SubnetSettlementHostStats) GetValidated() uint32 {
	if m != nil {
		return m.Validated
	}
	return 0
}

type SubnetSlotSignature struct {
	SlotId    uint32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SubnetSlotSignature) Reset()         { *m = SubnetSlotSignature{} }
func (m *SubnetSlotSignature) String() string { return proto.CompactTextString(m) }
func (*SubnetSlotSignature) ProtoMessage()    {}
func (*SubnetSlotSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9df301d9fc443f7, []int{3}
}
func (m *SubnetSlotSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetSlotSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetSlotSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetSlotSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetSlotSignature.Merge(m, src)
}
func (m *SubnetSlotSignature) XXX_Size() int {
	return m.Size()
}
func (m *SubnetSlotSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetSlotSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetSlotSignature proto.InternalMessageInfo

func (m *SubnetSlotSignature) GetSlotId() uint32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SubnetSlotSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SubnetEscrow)(nil), "inference.inference.SubnetEscrow")
	proto.RegisterType((*SubnetHostEpochStats)(nil), "inference.inference.SubnetHostEpochStats")
	proto.RegisterType((*SubnetSettlementHostStats)(nil), "inference.inference.SubnetSettlementHostStats")
	proto.RegisterType((*SubnetSlotSignature)(nil), "inference.inference.SubnetSlotSignature")
}

func init() {
	proto.RegisterFile("inference/inference/subnet_escrow.proto", fileDescriptor_a9df301d9fc443f7)
}

var fileDescriptor_a9df301d9fc443f7 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x6b, 0x27, 0x71, 0xe2, 0x49, 0xd2, 0x9f, 0xb4, 0xc9, 0xaf, 0xb8, 0x52, 0x65, 0x42,
	0x2e, 0xcd, 0x29, 0x15, 0xaa, 0x78, 0x01, 0x50, 0xa5, 0x56, 0x42, 0x02, 0x39, 0x12, 0x07, 0x2e,
	0xd6, 0x66, 0xbd, 0x34, 0x2b, 0x92, 0xdd, 0x65, 0x77, 0x0d, 0xe5, 0x2d, 0x78, 0x0d, 0xde, 0x84,
	0x63, 0x8f, 0x5c, 0x90, 0x50, 0xf2, 0x04, 0xbc, 0x01, 0xf2, 0xd8, 0xf9, 0xa3, 0xd0, 0x02, 0xe2,
	0x36, 0xf3, 0x9d, 0xef, 0x78, 0x67, 0x3f, 0x3b, 0x32, 0x9c, 0x0a, 0xf9, 0x86, 0x1b, 0x2e, 0x19,
	0x3f, 0xdb, 0x46, 0x36, 0x9f, 0x4a, 0xee, 0x52, 0x6e, 0x99, 0x51, 0x1f, 0xc6, 0xda, 0x28, 0xa7,
	0x48, 0x6f, 0x53, 0x1e, 0x6f, 0xa2, 0xe1, 0x37, 0x0f, 0x3a, 0x13, 0x34, 0x5f, 0xa0, 0x97, 0x1c,
	0x82, 0x2f, 0xb2, 0xc8, 0x1b, 0x78, 0xa3, 0x7a, 0xe2, 0x8b, 0x8c, 0x44, 0xd0, 0x64, 0x86, 0x53,
	0xa7, 0x4c, 0xe4, 0x0f, 0xbc, 0x51, 0x98, 0xac, 0x53, 0x72, 0x04, 0x01, 0x5d, 0xa8, 0x5c, 0xba,
	0xa8, 0x86, 0xee, 0x2a, 0x23, 0x7d, 0x68, 0xd8, 0xb9, 0x72, 0x36, 0xaa, 0x0f, 0x6a, 0xa3, 0x30,
	0x29, 0x13, 0xf2, 0x10, 0xda, 0x5c, 0x2b, 0x36, 0x4b, 0x85, 0xcc, 0xf8, 0x4d, 0xd4, 0xc0, 0x16,
	0x40, 0xe9, 0xaa, 0x50, 0xc8, 0x31, 0xb4, 0xa8, 0xd6, 0xe9, 0x8c, 0xda, 0x59, 0x14, 0x94, 0x27,
	0x51, 0xad, 0x2f, 0xa9, 0x9d, 0x15, 0x33, 0x58, 0xee, 0xdc, 0x9c, 0x67, 0x51, 0x73, 0xe0, 0x8d,
	0x5a, 0xc9, 0x3a, 0x2d, 0xbe, 0xea, 0xd4, 0x5b, 0x2e, 0x53, 0x6d, 0x04, 0xe3, 0x51, 0xab, 0xfc,
	0x2a, 0x4a, 0x2f, 0x0b, 0x65, 0xf8, 0xc3, 0x87, 0x7e, 0x79, 0xbf, 0x4b, 0x65, 0xdd, 0x45, 0x71,
	0xdc, 0xc4, 0x51, 0x67, 0xc9, 0x00, 0xda, 0x9a, 0x1a, 0x27, 0x98, 0xd0, 0x54, 0x3a, 0xbc, 0x70,
	0x98, 0xec, 0x4a, 0xfb, 0x13, 0xfb, 0xbf, 0x4c, 0x7c, 0x04, 0xc1, 0x42, 0x58, 0xcb, 0x33, 0x04,
	0xd0, 0x4d, 0xaa, 0xac, 0x18, 0x57, 0xc8, 0xf7, 0x74, 0x2e, 0xb2, 0xa8, 0x8e, 0x85, 0x75, 0x4a,
	0x08, 0xd4, 0x99, 0xb2, 0xae, 0xba, 0x3d, 0xc6, 0xe4, 0x31, 0xf4, 0x0d, 0x7f, 0x97, 0x0b, 0xc3,
	0xb3, 0x14, 0x5d, 0xd4, 0x09, 0x25, 0x2d, 0x32, 0xe8, 0x26, 0xbd, 0x75, 0xed, 0xd5, 0xb6, 0x44,
	0xce, 0xe1, 0x7f, 0xa6, 0x16, 0x7a, 0xce, 0xdd, 0x5e, 0x4f, 0x13, 0x7b, 0xfa, 0x9b, 0xe2, 0x6e,
	0xd3, 0x23, 0xe8, 0x94, 0xeb, 0x90, 0x32, 0x7c, 0xb4, 0x16, 0x7a, 0xdb, 0xa5, 0xf6, 0x0c, 0x5f,
	0xee, 0x14, 0xfe, 0xdb, 0x6c, 0x46, 0xe5, 0x0a, 0xd1, 0x75, 0xb8, 0x91, 0x4b, 0xe3, 0x09, 0x84,
	0xd5, 0xb1, 0x3c, 0x8b, 0x00, 0x2d, 0x5b, 0x61, 0xf8, 0xd9, 0x87, 0xe3, 0x92, 0xf9, 0x04, 0x9f,
	0x69, 0xc1, 0x25, 0xd2, 0x2f, 0xc1, 0x3f, 0x80, 0x66, 0xb1, 0x11, 0x69, 0xb5, 0x65, 0xdd, 0x24,
	0x28, 0xd2, 0xab, 0x6c, 0x07, 0xa7, 0x7f, 0x1f, 0xce, 0xda, 0xdd, 0x38, 0xeb, 0x7f, 0x81, 0xb3,
	0xf1, 0x0f, 0x38, 0x83, 0xdf, 0xe0, 0xbc, 0x83, 0x55, 0xf3, 0xcf, 0xac, 0x5a, 0xfb, 0xac, 0x9e,
	0x43, 0xaf, 0x42, 0x35, 0x57, 0x6e, 0x22, 0xae, 0x25, 0x75, 0xb9, 0xe1, 0xf7, 0x43, 0x3a, 0x81,
	0xd0, 0xae, 0x5d, 0xc8, 0xa9, 0x93, 0x6c, 0x85, 0xa7, 0x2f, 0xbe, 0x2c, 0x63, 0xef, 0x76, 0x19,
	0x7b, 0xdf, 0x97, 0xb1, 0xf7, 0x69, 0x15, 0x1f, 0xdc, 0xae, 0xe2, 0x83, 0xaf, 0xab, 0xf8, 0xe0,
	0xf5, 0x93, 0x6b, 0xe1, 0x66, 0xf9, 0x74, 0xcc, 0xd4, 0xe2, 0x4c, 0x1b, 0x95, 0xe5, 0xcc, 0x59,
	0x26, 0xf6, 0xfe, 0x1a, 0x37, 0x3b, 0xb1, 0xfb, 0xa8, 0xb9, 0x9d, 0x06, 0xf8, 0xeb, 0x38, 0xff,
	0x19, 0x00, 0x00, 0xff, 0xff, 0x10, 0x6d, 0xf6, 0x08, 0x65, 0x04, 0x00, 0x00,
}

func (m *SubnetEscrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetEscrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetEscrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenPrice != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.TokenPrice))
		i--
		dAtA[i] = 0x40
	}
	if m.Settled {
		i--
		if m.Settled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.AppHash) > 0 {
		i -= len(m.AppHash)
		copy(dAtA[i:], m.AppHash)
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(len(m.AppHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.EpochIndex != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.EpochIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Slots) > 0 {
		for iNdEx := len(m.Slots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Slots[iNdEx])
			copy(dAtA[i:], m.Slots[iNdEx])
			i = encodeVarintSubnetEscrow(dAtA, i, uint64(len(m.Slots[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Amount != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubnetHostEpochStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetHostEpochStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetHostEpochStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Validated != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Validated))
		i--
		dAtA[i] = 0x50
	}
	if m.InferenceCount != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.InferenceCount))
		i--
		dAtA[i] = 0x48
	}
	if m.EscrowCount != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.EscrowCount))
		i--
		dAtA[i] = 0x40
	}
	if m.CompletedValidations != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.CompletedValidations))
		i--
		dAtA[i] = 0x38
	}
	if m.RequiredValidations != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.RequiredValidations))
		i--
		dAtA[i] = 0x30
	}
	if m.Cost != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x28
	}
	if m.Invalid != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Invalid))
		i--
		dAtA[i] = 0x20
	}
	if m.Missed != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Missed))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochIndex != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.EpochIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubnetSettlementHostStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetSettlementHostStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetSettlementHostStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Validated != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Validated))
		i--
		dAtA[i] = 0x40
	}
	if m.InferenceCount != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.InferenceCount))
		i--
		dAtA[i] = 0x38
	}
	if m.CompletedValidations != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.CompletedValidations))
		i--
		dAtA[i] = 0x30
	}
	if m.RequiredValidations != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.RequiredValidations))
		i--
		dAtA[i] = 0x28
	}
	if m.Cost != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x20
	}
	if m.Invalid != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Invalid))
		i--
		dAtA[i] = 0x18
	}
	if m.Missed != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.Missed))
		i--
		dAtA[i] = 0x10
	}
	if m.SlotId != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubnetSlotSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetSlotSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetSlotSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.SlotId != 0 {
		i = encodeVarintSubnetEscrow(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSubnetEscrow(dAtA []byte, offset int, v uint64) int {
	offset -= sovSubnetEscrow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubnetEscrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovSubnetEscrow(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Amount))
	}
	if len(m.Slots) > 0 {
		for _, s := range m.Slots {
			l = len(s)
			n += 1 + l + sovSubnetEscrow(uint64(l))
		}
	}
	if m.EpochIndex != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.EpochIndex))
	}
	l = len(m.AppHash)
	if l > 0 {
		n += 1 + l + sovSubnetEscrow(uint64(l))
	}
	if m.Settled {
		n += 2
	}
	if m.TokenPrice != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.TokenPrice))
	}
	return n
}

func (m *SubnetHostEpochStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovSubnetEscrow(uint64(l))
	}
	if m.EpochIndex != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.EpochIndex))
	}
	if m.Missed != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Missed))
	}
	if m.Invalid != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Invalid))
	}
	if m.Cost != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Cost))
	}
	if m.RequiredValidations != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.RequiredValidations))
	}
	if m.CompletedValidations != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.CompletedValidations))
	}
	if m.EscrowCount != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.EscrowCount))
	}
	if m.InferenceCount != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.InferenceCount))
	}
	if m.Validated != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Validated))
	}
	return n
}

func (m *SubnetSettlementHostStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.SlotId))
	}
	if m.Missed != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Missed))
	}
	if m.Invalid != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Invalid))
	}
	if m.Cost != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Cost))
	}
	if m.RequiredValidations != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.RequiredValidations))
	}
	if m.CompletedValidations != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.CompletedValidations))
	}
	if m.InferenceCount != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.InferenceCount))
	}
	if m.Validated != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.Validated))
	}
	return n
}

func (m *SubnetSlotSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovSubnetEscrow(uint64(m.SlotId))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSubnetEscrow(uint64(l))
	}
	return n
}

func sovSubnetEscrow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSubnetEscrow(x uint64) (n int) {
	return sovSubnetEscrow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubnetEscrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetEscrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetEscrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slots", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slots = append(m.Slots, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
			}
			m.EpochIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Settled = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenPrice", wireType)
			}
			m.TokenPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetHostEpochStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetHostEpochStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetHostEpochStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
			}
			m.EpochIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Missed", wireType)
			}
			m.Missed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Missed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invalid", wireType)
			}
			m.Invalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Invalid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredValidations", wireType)
			}
			m.RequiredValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedValidations", wireType)
			}
			m.CompletedValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowCount", wireType)
			}
			m.EscrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscrowCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceCount", wireType)
			}
			m.InferenceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InferenceCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validated", wireType)
			}
			m.Validated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Validated |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetSettlementHostStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetSettlementHostStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetSettlementHostStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Missed", wireType)
			}
			m.Missed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Missed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invalid", wireType)
			}
			m.Invalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Invalid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredValidations", wireType)
			}
			m.RequiredValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedValidations", wireType)
			}
			m.CompletedValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceCount", wireType)
			}
			m.InferenceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InferenceCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validated", wireType)
			}
			m.Validated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Validated |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetSlotSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetSlotSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetSlotSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSubnetEscrow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSubnetEscrow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubnetEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSubnetEscrow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSubnetEscrow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSubnetEscrow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSubnetEscrow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSubnetEscrow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSubnetEscrow = fmt.Errorf("proto: unexpected end of group")
)
